# Generated by Django 5.2.16 on 2026-07-24 00:03

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import operations.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('precutover', 'Pre-corte'), ('final', 'Final')], max_length=20)),
                ('source_path', models.CharField(max_length=500)),
                ('dry_run', models.BooleanField(default=False)),
                ('status', models.CharField(default='RUNNING', max_length=20)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('report_path', models.CharField(blank=True, max_length=500)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('must_change_password', models.BooleanField(default=True)),
                ('session_version', models.PositiveIntegerField(default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'permissions': [('manage_users', 'Puede administrar usuarios'), ('manage_roles', 'Puede administrar roles y permisos')],
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('object_type', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=180)),
                ('phone', models.CharField(max_length=32)),
                ('normalized_phone', models.CharField(db_index=True, editable=False, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('dni', models.CharField(blank=True, max_length=32)),
                ('normalized_dni', models.CharField(blank=True, db_index=True, editable=False, max_length=32)),
                ('is_delinquent', models.BooleanField(default=False)),
                ('condition', models.CharField(blank=True, max_length=200)),
                ('legacy_duplicate_allowed', models.BooleanField(default=False)),
                ('legacy_locked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'permissions': [('archive_client', 'Puede archivar clientes'), ('restore_client', 'Puede restaurar clientes')],
                'indexes': [models.Index(fields=['normalized_phone', 'archived_at'], name='operations__normali_a5e192_idx'), models.Index(fields=['normalized_dni', 'archived_at'], name='operations__normali_6a9d8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('full_text', models.CharField(db_index=True, max_length=320)),
                ('reference', models.CharField(blank=True, max_length=240)),
                ('legacy_locked', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='operations.client')),
            ],
            options={
                'ordering': ['full_text'],
                'permissions': [('archive_address', 'Puede archivar direcciones'), ('restore_address', 'Puede restaurar direcciones')],
            },
        ),
        migrations.CreateModel(
            name='DataIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(db_index=True, max_length=80)),
                ('row_reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('issue_type', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.URLField(max_length=1000, unique=True)),
                ('p256dh', models.TextField()),
                ('auth', models.TextField()),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('legacy_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('legacy_row_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('client_name_snapshot', models.CharField(blank=True, max_length=180)),
                ('client_phone_snapshot', models.CharField(blank=True, max_length=32)),
                ('address_snapshot', models.CharField(blank=True, max_length=320)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('description', models.CharField(max_length=500)),
                ('admin_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ASSIGNED', 'Asignado'), ('IN_PROGRESS', 'En curso'), ('COMPLETED', 'Finalizado'), ('CANCELLED', 'Cancelado')], db_index=True, default='PENDING', max_length=20)),
                ('arrival_at', models.DateTimeField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('requires_review', models.BooleanField(db_index=True, default=False)),
                ('legacy_locked', models.BooleanField(default=False)),
                ('legacy_raw_timestamps', models.JSONField(blank=True, default=dict)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='operations.address')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='operations.client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at', '-created_at'],
                'permissions': [('assign_service', 'Puede asignar servicios'), ('arrive_service', 'Puede marcar llegada'), ('complete_service', 'Puede finalizar servicios'), ('cancel_service', 'Puede cancelar servicios'), ('reopen_service', 'Puede reabrir servicios'), ('override_overlap', 'Puede confirmar solapamientos'), ('archive_service', 'Puede archivar servicios'), ('view_dashboard', 'Puede ver el tablero operativo')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('voided_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=300)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments_recorded', to=settings.AUTH_USER_MODEL)),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments_voided', to=settings.AUTH_USER_MODEL)),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='operations.paymentmethod')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='operations.service')),
            ],
            options={
                'ordering': ['-paid_at', '-created_at'],
                'permissions': [('view_billing', 'Puede ver importes y cobros'), ('manage_billing', 'Puede registrar y anular cobros'), ('view_daily_cash', 'Puede ver la caja diaria')],
            },
        ),
        migrations.CreateModel(
            name='ServiceEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('CREATED', 'Creado'), ('ASSIGNED', 'Asignado'), ('REASSIGNED', 'Reasignado'), ('RESCHEDULED', 'Reprogramado'), ('ARRIVED', 'Llegada'), ('NOTE_ADDED', 'Observación'), ('COMPLETED', 'Finalizado'), ('CANCELLED', 'Cancelado'), ('REOPENED', 'Reabierto'), ('ARCHIVED', 'Archivado'), ('RESTORED', 'Restaurado'), ('CONFLICT', 'Conflicto')], db_index=True, max_length=24)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='operations.service')),
            ],
            options={
                'ordering': ['occurred_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=operations.models.service_photo_path)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('legacy_url', models.URLField(blank=True, max_length=1000)),
                ('caption', models.CharField(blank=True, max_length=240)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='operations.service')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_id', models.UUIDField(db_index=True, unique=True)),
                ('operation_type', models.CharField(choices=[('ARRIVE', 'Llegada'), ('ADD_NOTE', 'Agregar observación'), ('COMPLETE', 'Finalizar')], max_length=20)),
                ('base_version', models.PositiveIntegerField()),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('APPLIED', 'Aplicada'), ('DUPLICATE', 'Duplicada'), ('CONFLICT', 'Conflicto'), ('FAILED', 'Fallida')], max_length=20)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_operations', to='operations.service')),
            ],
            options={
                'ordering': ['received_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(max_length=300)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='operations.service')),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conflict', to='operations.syncoperation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('display_name', models.CharField(db_index=True, max_length=180)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(db_index=True, default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='operations.technicianprofile'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['scheduled_at', 'status'], name='operations__schedul_edbc69_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['assigned_technician', 'scheduled_at'], name='operations__assigne_6b9ca4_idx'),
        ),
    ]
