# Generated by Django 5.2.16 on 2026-07-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_servicephoto_client_operation_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'permissions': [('archive_client', 'Puede archivar clientes'), ('restore_client', 'Puede restaurar clientes'), ('view_client_sensitive', 'Puede ver datos sensibles de clientes')]},
        ),
    ]
